# Generated by Django 3.0.2 on 2020-01-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Album',
            new_name='album',
        ),
    ]
